[package]
name = "sample-cgi-script"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
axum = "0.8.1"
tower-cgi = { path = "../tower-cgi" }
tokio = { version = "1", features = ["full"] }
